services:
  gedmo.mapping.driver.attribute:
    class: Gedmo\Mapping\Driver\AttributeReader

  Gedmo\Loggable\LoggableListener:
    tags:
      - { name: doctrine.event_listener, event: 'onFlush' }
      - { name: doctrine.event_listener, event: 'loadClassMetadata' }
      - { name: doctrine.event_listener, event: 'postPersist' }
    calls:
      - [ setAnnotationReader, [ "@gedmo.mapping.driver.attribute" ] ]