services:
  Gedmo\Loggable\LoggableListener:
    tags:
      - {
        name: doctrine.event_subscriber,
        connection: default
      }
    calls:
      - [ setAnnotationReader, [ "@annotation_reader" ] ]