services:
  gedmo.mapping.driver.attribute:
    class: Gedmo\Mapping\Driver\AttributeReader

  Gedmo\Loggable\LoggableListener:
    tags:
      - {
        name: doctrine.event_subscriber,
        connection: default
      }
    calls:
      - [ setAnnotationReader, [ "@gedmo.mapping.driver.attribute" ] ]