doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations2023': '%kernel.project_dir%/migrations/Migration2023'
        'DoctrineMigrations': '%kernel.project_dir%/migrations/MigrationOld'

    services:
        'Doctrine\Migrations\Version\Comparator': "App\\Service\\Doctrine\\Migrations\\Version\\Comparator"
