<?php
declare(strict_types=1);

namespace App\Entity\Table;

class UrlColumn extends Column
{
    public function getRender(object $row): mixed
    {
        return parent::getRender($row); // TODO: Change the autogenerated stub
    }
}